version: '2'
services:
  registry:
    image: registry:latest
    restart: always
    container_name: registry
    ports:
      - "5000:5000"
#    environment:
#      REGISTRY_HTTP_TLS_CERTIFICATE: /certs/domain.crt
#      REGISTRY_HTTP_TLS_KEY: /certs/domain.key
#    volumes:
#      - "/private/amd/registry:/var/lib/registry"
#      - "/certs:/certs"

  mongo:
    image: aashreys/mongo-auth:latest
    hostname: mongo
    environment:
      - AUTH=yes
      - MONGODB_ADMIN_USER=admin
      - MONGODB_ADMIN_PASS=notasecret
      - MONGODB_APPLICATION_DATABASE=amd
      - MONGODB_APPLICATION_USER=amd
      - MONGODB_APPLICATION_PASS=amd@dmin
    restart: always
    ports:
      - "27017:27017"
      
  mongo-ui:
    image: mongo-express:latest
    hostname: mongo-ui
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=notasecret
      - ME_CONFIG_BASICAUTH_USERNAME=amd
      - ME_CONFIG_BASICAUTH_PASSWORD=amd@dmin
    restart: always
    ports:
      - "8081:8081"
  
  amd:
    image: localhost:5000/amd/com.amdinstallation.service.web:latest
    restart: always
    container_name: amd
    ports:
      - "80:8080"
      - "443:443"
    links:
      - mongo
    environment:
      - LOGGING_LEVEL=DEBUG
 