package com.amdinstallation.web.model;

public enum Model {
	CHEVELLE, CAMARO, NOVA, LE_MANS, BARRACUDA, SKYLARK, CUTLASS, CHALLENGER, CHARGER, ROAD_RUNNER, MONTE_CARLO,
	DART, DEMON, DUSTER, SCAMP, VALIANT, CORONET, BELVEDERE, GTX, SATELLITE, SUPERBIRD, DAYTONA, CHEVY_II, MALIBU,
	EL_CAMINO, FIREBIRD, TRANS_AM, GTO, POLARA, FURY, SAVOY, GS, GSX, O442, SPECIAL, GRAND_PRIX, LEMANS, TEMPEST,
	IMPALA, BEL_AIR, BISCAYNE, CAPRICE, SAFARI
}
