export default [
{text: "Adult Content", value: "ADULT_CONTENT"},
{text: "Adult - Download", value: "ADULT_DOWNLOAD"},
{text: "Adult - Physical", value: "ADULT_PHYSICAL"},
{text: "Adult - Service", value: "ADULT_SERVICE"},
{text: "Adult - Streaming", value: "ADULT_STREAMING"},
{text: "Adult - Text", value: "ADULT_TEXT"},
{text: "Alcohol", value: "ALCOHOL"},
{text: "Aggregation", value: "AGGREGATION"},
{text: "Alcohol - Delivery", value: "ALCOHOL_DELIVERY"},
{text: "Alcohol - In Person", value: "ALCOHOL_IN_PERSON"},
{text: "Child Exploitation - Download", value: "CE_DOWNLOAD"},
{text: "Child Exploitation - Physical", value: "CE_PHYSICAL"},
{text: "Child Exploitation - Service", value: "CE_SERVICE"},
{text: "Child Exploitation - Streaming", value: "CE_STREAMING"},
{text: "Child Exploitation - Text", value: "CE_TEXT"},
{text: "Circumvention Products", value: "CIRCUMVENTION_PRODUCTS"},
{text: "Circumvention Products - Card Sharing", value: "CP_CARD_SHARING"},
{text: "Circumvention Products - Emulator/ROM", value: "CP_EMULATOR_ROM"},
{text: "Circumvention Products - Key Vault", value: "CP_KEY_VAULT"},
{text: "Circumvention Products - Mod Chips", value: "CP_MOD_CHIPS"},
{text: "Circumvention Products - Ripper", value: "CP_RIPPER"},
{text: "Child Pornography - Download", value: "CHILD_PORN_DOWNLOAD"},
{text: "Child Pornography - Physical", value: "CHILD_PORN_PHYSICAL"},
{text: "Child Pornography - Service", value: "CHILD_PORN_SERVICE"},
{text: "Child Pornography - Streaming", value: "CHILD_PORN_STREAMING"},
{text: "Child Pornography - Text", value: "CHILD_PORN_TEXT"},
{text: "Credit Repair", value: "CREDIT_REPAIR"},
{text: "Credit Repair - Counseling/Repair", value: "CREDIT_REPAIR_COUNSELING"},
{text: "Credit Repair - Loan Modification", value: "CREDIT_REPAIR_LOAN_MODIFICATION"},
{text: "Credit Repair - Tradelines", value: "CREDIT_REPAIR_TRADELINES"},
{text: "Drugs - Cannabis", value: "DRUGS_CANNABIS"},
{text: "Drugs - Cannabis Related", value: "DRUGS_CANNABIS_RELATED"},
{text: "Drugs - Cannabis Seeds", value: "DRUGS_CANNABIS_SEEDS"},
{text: "Drugs - Mushrooms / Spores", value: "DRUGS_MUSHROOMS_SPORES"},
{text: "Drugs - Other Prohibited Plant Products", value: "DRUGS_PROHIBITED_PLANTS"},
{text: "Drugs - Other Scheduled Drugs", value: "DRUGS_SCHEDULED"},
{text: "Drugs - Paraphernalia", value: "ILLEGAL_DRUGS_PARAPHERNALIA"},
{text: "Drugs - Poppers", value: "DRUGS_POPPERS"},
{text: "Drugs - Steriods", value: "DRUGS_STEROIDS"},
{text: "Drugs - Synthetic Drugs", value: "DRUGS_SYNTHETIC"},
{text: "E-Cigarettes", value: "E_CIGARETTE"},
{text: "Encourages Illegal Activity", value: "ENCOURAGE_ILLEGAL_ACTIVITY"},
{text: "Encourages Illegal Activity - DDOS", value: "EIA_DDOS"},
{text: "Encourages Illegal Activity - Drug Test Circumvention", value: "EIA_DRUG_TEST_CIRCUMVENTION"},
{text: "Encourages Illegal Activity - Forged Documentation", value: "EIA_FORGED_DOCUMENTATION"},
{text: "Encourages Illegal Activity - Illegal Activity Forums", value: "EIA_FORUMS"},
{text: "Encourages Illegal Activity - Key Loggers", value: "EIA_KEY_LOGGERS"},
{text: "Encourages Illegal Activity - Online Account Sales", value: "EIA_ONLINE_ACCOUNT_SALES"},
{text: "Encourages Illegal Activity - Restriction Circumvention", value: "EIA_RESTRICTION_CIRCUMVENTION"},
{text: "Encourages Illegal Activity - Security Device Circumvention", value: "EIA_SECURITY_DEVICE_CIRCUMVENTION"},
{text: "Encourages Illegal Activity - Signal Jammers", value: "EIA_SIGNAL_JAMMERS"},
{text: "Event Tickets", value: "EVENT_TICKETS"},
{text: "File Sharing - Bit Torrent / Peer to Peer", value: "FILE_SHARING_TORRENT_P2P"},
{text: "File Sharing - Cyber Locker", value: "FILE_SHARING_CYBER_LOCKER"},
{text: "File Sharing - Third Party Sales", value: "FILE_SHARING_THIRD_PARTY_SALES"},
{text: "File Sharing - Usenet", value: "FILE_SHARING_USENET"},
{text: "Weapons - Firearms", value: "FIREARMS"},
{text: "Gambling", value: "GAMBLING"},
{text: "Gambling - Fantasy Sports", value: "GAMBLING_FANTASY_SPORTS"},
{text: "Gambling - Games of Chance", value: "GAMBLING_GAMES_OF_CHANCE"},
{text: "Gambling - Games of Skill", value: "GAMBLING_GAMES_OF_SKILL"},
{text: "Gambling - Lotteries and Raffle", value: "GAMBLING_LOTTERY_RAFFLE"},
{text: "Gambling - Related Ventures", value: "GAMBLING_RELATED_VENTURES"},
{text: "High Risk Adult - Bestiality", value: "HRA_BESTIALITY"},
{text: "High Risk Adult - Crushing", value: "HRA_CRUSHING"},
{text: "High Risk Adult - Incest", value: "HRA_INCEST"},
{text: "High Risk Adult - Rape", value: "HRA_RAPE"},
{text: "High Risk Adult - Snuff", value: "HRA_SNUFF"},
{text: "IP Infringement - Bootleg Recordings", value: "IP_BOOTLEG"},
{text: "IP Infringement - Clothing", value: "IP_CLOTHING"},
{text: "IP Infringement - Cosmetics", value: "IP_COSMETICS"},
{text: "IP Infringement - Download Movies", value: "IP_DOWNLOAD_MOVIES"},
{text: "IP Infringement - Download Music", value: "IP_DOWNLOAD_MUSIC"},
{text: "IP Infringement - Download Other", value: "IP_DOWNLOAD_OTHER"},
{text: "IP Infringement - Download Software", value: "IP_DOWNLOAD_SOFTWARE"},
{text: "IP Infringement - Download Sports", value: "IP_DOWNLOAD_SPORTS"},
{text: "IP Infringement - Download Television", value: "IP_DOWNLOAD_TV"},
{text: "IP Infringement - Headphones", value: "IP_HEADPHONES"},
{text: "IP Infringement - Jewelry", value: "IP_JEWELRY"},
{text: "IP Infringement - Physical Movies", value: "IP_PHYSICAL_MOVIES"},
{text: "IP Infringement - Physical Music", value: "IP_PHYSICAL_MUSIC"},
{text: "IP Infringement - Physical Other", value: "IP_PHYSICAL_OTHER"},
{text: "IP Infringement - Physical Software", value: "IP_PHYSICAL_SOFTWARE"},
{text: "IP Infringement - Physical Sports", value: "IP_PHYSICAL_SPORTS"},
{text: "IP Infringement - Physical Television", value: "IP_PHYSICAL_TV"},
{text: "IP Infringement - Shoes", value: "IP_SHOES"},
{text: "IP Infringement - Smartphone Accessories", value: "IP_SMARTPHONE_ACC"},
{text: "IP Infringement - Smartphones", value: "IP_SMARTPHONES"},
{text: "IP Infringement - Streaming Movies", value: "IP_STREAMING_MOVIES"},
{text: "IP Infringement - Streaming Music", value: "IP_STREAMING_MUSIC"},
{text: "IP Infringement - Streaming Other", value: "IP_STREAMING_OTHER"},
{text: "IP Infringement - Streaming Sports", value: "IP_STREAMING_SPORTS"},
{text: "IP Infringement - Streaming Television", value: "IP_STREAMING_TV"},
{text: "IP Infringement - Sunglasses", value: "IP_SUNGLASSES"},
{text: "IP Infringement - Test Banks", value: "IP_TEST_BANKS"},
{text: "IP Infringement - Watches", value: "IP_WATCHES"},
{text: "Multi-Level Marketing - Get Rich Quick", value: "GRQ_SCHEME"},
{text: "Medical - Devices", value: "MEDICAL_DEVICES"},
{text: "Medical - Services", value: "MEDICAL_SERVICES"},
{text: "Multi-Level Marketing", value: "MLM"},
{text: "Multi-Level Marketing - Add Me To Your List", value: "MLM_AMTYL"},
{text: "Multi-Level Marketing - Auto Surf / Paid To Click", value: "MLM_AUTO_SURF"},
{text: "Multi-Level Marketing - High Yield Investment Program", value: "MLM_HYIP"},
{text: "Multi-Level Marketing - Matrix", value: "MLM_MATRIX"},
{text: "Multi-Level Marketing - Pyramid", value: "MLM_PYRAMID"},
{text: "Multi-Level Marketing - Randomizer", value: "MLM_RANDOMIZER"},
{text: "Mugshot / Arrest Record Removal", value: "MUGSHOT_ARREST_RECORD_REMOVAL"},
{text: "Offensive", value: "OFFENSIVE"},
{text: "Personal Information - Password Circumvention", value: "PI_PWD_CIRCUMVENTION"},
{text: "Personal Information - Phone Records", value: "PI_PHONE_RECORDS"},
{text: "Pharmaceutical", value: "PHARMACEUTICAL"},
{text: "Pharmaceutical - HGH / HCG", value: "PHARMA_HGH_HCG"},
{text: "Pharmaceutical - Prescription Drugs", value: "PHARMA_PRESCRIPTION"},
{text: "Pharmaceutical - Unapproved Drugs", value: "PHARMA_UNAPPROVED_DRUGS"},
{text: "Pharmaceutical - Undeclared Sexual Health", value: "PHARMA_SEX_HEALTH"},
{text: "Pharmaceutical - Undeclared Weight Loss", value: "PHARMA_WEIGHT_LOSS"},
{text: "Pharmaceutical - Veterinary Products", value: "PHARMA_VET_PRODUCTS"},
{text: "Stolen Digital Goods", value: "STOLEN_DIGITAL_GOODS"},
{text: "Tobacco", value: "TOBACCO"},
{text: "Tobacco - Cigar", value: "TOBACCO_CIGAR"},
{text: "Tobacco - Cigarettes", value: "TOBACCO_CIGARETTES"},
{text: "Tobacco - Pipe Tobacco", value: "TOBACCO_PIPE"},
{text: "Tobacco - Shisha", value: "TOBACCO_SHISHA"},
{text: "Tobacco - Smokeless", value: "TOBACCO_SMOKELESS"},
{text: "Weapons - Ammunition", value: "WEAPONS_AMMO"},
{text: "Weapons - DD/Militaria/Ordinance", value: "WEAPONS_DD"},
{text: "Weapons - Firearms Parts and Accessories", value: "WEAPONS_PARTS"},
{text: "Weapons - Knives", value: "WEAPONS_KNIVES"},
{text: "Weapons - NonKnife Hand Weapons", value: "WEAPONS_NON_KNIFE"}
];
